# Generated by Django 4.2.3 on 2023-07-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0002_inventario_ventas_rename_operador_personal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='antiguedad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='puesto',
            field=models.CharField(default='Sin puesto', max_length=230),
        ),
    ]
