# Generated by Django 4.2.3 on 2023-08-06 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Personal', '0003_personal_antiguedad_personal_puesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='personas_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
