# Generated by Django 4.2.3 on 2023-08-11 01:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0004_personal_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='codigo',
            field=models.CharField(max_length=230, validators=[django.core.validators.RegexValidator(message='El código debe contener números, guiones y letras.', regex='^[0-9A-Za-z\\-_.,]+$')]),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='localizador',
            field=models.TextField(null=True),
        ),
    ]
