# Generated by Django 4.2.3 on 2023-08-12 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0005_alter_inventario_codigo_alter_inventario_localizador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='codigo',
            field=models.CharField(max_length=230, validators=[django.core.validators.RegexValidator(message='El código debe contener números, guiones, letras y símbolos.', regex='^[0-9A-Za-z\\-_.,]+$')]),
        ),
    ]
