# Generated by Django 4.2.3 on 2023-08-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0007_inventario_ea_alter_inventario_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='comentario',
            field=models.CharField(default='NC', max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ea',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='localizador',
            field=models.CharField(max_length=54),
        ),
    ]
