# Generated by Django 4.2.3 on 2023-08-12 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Personal', '0008_inventario_comentario_alter_inventario_ea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materiales_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
