# Generated by Django 4.2.3 on 2023-08-12 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0009_inventario_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='codigo_cliente',
            field=models.CharField(default='08082023', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventas',
            name='fecha_venta',
            field=models.DateField(default=datetime.date(2023, 8, 12)),
        ),
    ]
