# Generated by Django 4.2.3 on 2023-08-13 11:33

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0011_alter_ventas_fecha_venta_historialinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
